name: Manual Blog Sync

on: 
  workflow_dispatch:
  
  workflow_call:
  
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/blog-post-workflow.yml
  
